import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

// Copy PDF.js worker to src for bundling
try {
	fs.copyFileSync(
		'node_modules/pdfjs-dist/build/pdf.worker.min.mjs',
		'src/pdf.worker.min.workerjs'
	);
	console.log("Prepared pdf.worker.min.workerjs for bundling");
} catch (e) {
	console.error("Failed to prepare PDF worker:", e);
}

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2020',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	loader: {
		'.wasm': 'binary',
		'.workerjs': 'text'
	},
	define: {
		'import.meta.url': '"obsidian-plugin"'
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
